{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.applicationName }}
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.applicationName }}
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.applicationName }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}

